config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "homes#top"
  end

  get "/admin/recent_registrated_reservation" => "admin/homes#about", as: "admin_about"

  root to: "public/homes#top"
  get "/fee" => "public/homes#about", as: "fee"
  get "/lane_status" => "public/homes#lane_status", as: "lane_status"
  get "/map" => "public/homes#map", as: "map"

  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :notifications, only: [:index]
  end

  post "/admin/num_lanes" => "admin/start_dates#num_lanes", as: "admin_num_lanes"
  namespace :admin do
    resources :start_dates, only: [:create, :index, :show, :edit, :update]
  end

  namespace :admin do
    resources :reservations, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: "public" do
    resources :reviews, only: [:index, :create, :edit, :update, :destroy]
  end

  get "/users/my_page" => "public/users#show", as: "my_page"
  get "/users/information/edit" => "public/users#edit", as: "edit_user_information"
  patch "/users/information" => "public/users#update", as: "update_user_information"

  scope module: "public" do
    resources :reservations, only: [:new, :index, :show]
  end
  post "/reservations/select_time" => "public/reservations#select_time", as: "select_time"
  post "/reservations/confirm" => "public/reservations#confirm", as: "confirm"
  post "/reservations/create" => "public/reservations#create", as: "create"
  post "/reservations/members_table" => "public/reservations#members_table", as: "members_table"
  get "/complete" => "public/reservations#complete", as: "complete"
  get "/reservations/:id/confirm_cancel" => "public/reservations#confirm_cancel", as: "confirm_cancel"
  patch "/reservations/:id/cancel" => "public/reservations#cancel", as: "cancel"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :lane_details, dependent: :destroy
  accepts_nested_attributes_for :lane_details, allow_destroy: true
  has_many :notifications, dependent: :destroy

  validates :group_name, presence: true
  validates :num_children, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_students, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_adults, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_games, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :num_lanes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :start_date, presence: true
  validates :start_time, presence: true, format: {with: /[1-2][0-9]:[0-5][0-9]/}
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  def index
    reservations = Reservation.page(params[:page]).where("start_date < ?", Date.current)
    @reservations = reservations.order(start_date: :desc, start_time: :desc)
  end

  def show
    @reservation = Reservation.find(params[:id])
    @lane_details = @reservation.lane_details.all
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @lane_details = @reservation.lane_details.all
  end

  def update
    @reservation = Reservation.find(params[:id])
    status = @reservation.is_active
    @lane_details = @reservation.lane_details.all
    @start_date = StartDate.find_by(start_date: @reservation.start_date)
    if @reservation.update(reservation_params)
      if @reservation.lane_details.presence && @reservation.lane_details[0].name_1.presence
        service_fee = (@reservation.num_children + @reservation.num_students + @reservation.num_adults) * 100
        fixed_games_fee = (@reservation.num_children * 400 + @reservation.num_students * 500 + @reservation.num_adults * 600) * @reservation.num_games - service_fee
      else
        fixed_games_fee = (@reservation.num_children * 400 + @reservation.num_students * 500 + @reservation.num_adults * 600) * @reservation.num_games
      end
      @reservation.update(games_fee: fixed_games_fee)
      @start_date.start_times.each do |start_time|
        time = start_time.start_time
        if time.strftime("%H:%M") == @reservation.start_time.strftime("%H:%M")
          # 「有効」から「キャンセル」に編集したとき
          if status == true && @reservation.is_active == false
            fixed_lanes = start_time.num_available_lanes + @reservation.num_lanes
            start_time.update(num_available_lanes: fixed_lanes)
          # 「キャンセル」から「有効」に編集したとき
          elsif status == false && @reservation.is_active == true
            fixed_lanes = start_time.num_available_lanes - @reservation.num_lanes
            start_time.update(num_available_lanes: fixed_lanes)
          end
        end
      end
      redirect_to admin_reservation_path(@reservation.id)
    else
      render :edit
    end
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to admin_root_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:group_name, :num_children, :num_students, :num_adults, :num_games, :num_lanes, :start_date, :start_time, :note, :games_fee, :is_active,
      lane_details_attributes: [:id, :name_1, :name_2, :name_3, :name_4]
    )
  end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/views/admin/reservations/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-12 text-center bg-light">
      <h2><%= @reservation.start_date %> <%= @reservation.group_name %>様の予約編集</h2>
      <% if @reservation.errors.any? %>
        <h4><%= @reservation.errors.count %>件のエラーが発生しました</h4>
        <ul>
          <% @reservation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @reservation, url: admin_reservation_path(@reservation.id), method: :patch do |f| %>
    <div class="row mt-4">
      <div class="col-8 mx-auto">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td class="bg-light">団体名</td>
              <td><%= f.text_field :group_name %> 様</td>
            </tr>
            <tr>
              <td class="bg-light">中学生以下の人数</td>
              <td><%= f.text_field :num_children %> 人</td>
            </tr>
            <tr>
              <td class="bg-light">高校・大学・専門学生の人数</td>
              <td><%= f.text_field :num_students %> 人</td>
            </tr>
            <tr>
              <td class="bg-light">一般の人数</td>
              <td><%= f.text_field :num_adults %> 人</td>
            </tr>
            <tr>
              <td class="bg-light">ゲーム数</td>
              <td><%= f.text_field :num_games %> ゲーム</td>
            </tr>
            <tr>
              <td class="bg-light">使用レーン数</td>
              <td><%= f.text_field :num_lanes %> レーン</td>
            </tr>
            <tr>
              <td class="bg-light">実施日</td>
              <td><%= f.date_field :start_date %></td>
            </tr>
            <tr>
              <td class="bg-light">スタート時間</td>
              <td><%= f.time_select :start_time, start_hour: 10, end_hour: 20, minute_step: 30 %></td>
            </tr>
            <tr>
              <td class="bg-light">ステータス</td>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "有効" %>
                <%= f.radio_button :is_active, false, class: "ml-4" %>
                <%= f.label :is_active_false, "キャンセル" %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <% if @lane_details.presence && @lane_details[0].name_1.presence %>
      <div class="row mt-4">
        <div class="col-12 mx-auto text-center">
          <table class="table table-bordered mt-2">
            <thead class="bg-light">
              <tr>
                <td></td>
                <td>第１投球者</td>
                <td>第２投球者</td>
                <td>第３投球者</td>
                <td>第４投球者</td>
              </tr>
            </thead>
            <tbody>
              <%= f.fields_for :lane_details do |field| %>
                <tr>
                  <td><%= field.index + 1 %> レーン</td>
                  <td><%= field.text_field :name_1, autofocus: true, style: "border: none; outline: none" %></td>
                  <td><%= field.text_field :name_2, style: "border: none; outline: none" %></td>
                  <td><%= field.text_field :name_3, style: "border: none; outline: none" %></td>
                  <td><%= field.text_field :name_4, style: "border: none; outline: none" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>

    <div class="row mt-2">
      <div class="col-8 mx-auto text-center">
        <%= f.submit "編集内容を保存", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/reservations/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-4 text-center bg-light">
      <h2>前日までの予約</h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12 mx-auto text-center">
            <table class="table table-bordered">
        <thead class="bg-light">
          <tr>
            <td scope="col" style="width: 15%">幹事</td>
            <td scope="col" style="width: 30%">団体名</td>
            <td scope="col" style="width: 15%">実施日</td>
            <td scope="col" style="width: 15%">スタート時間</td>
            <td scope="col" style="width: 10%">人数</td>
            <td scope="col" style="width: 15%">ステータス</td>
          </tr>
        </thead>
        <tbody>
          <% @reservations.each do |reservation| %>
            <% @start_date = StartDate.find_by(start_date: reservation.start_date) %>
            <tr>
              <td>
                <%= link_to(admin_user_path(reservation.user_id), style: "color: black; text-decoration: underline") do %>
                  <%= reservation.user.last_name %> <%= reservation.user.first_name %>
                <% end %>
              </td>
              <td>
                <%= link_to(admin_reservation_path(reservation.id), style: "color: black; text-decoration: underline") do %>
                  <%= reservation.group_name %>
                <% end %>
              </td>
              <td>
                <%= link_to(admin_start_date_path(@start_date.id), style: "color: black; text-decoration: underline") do %>
                  <%= reservation.start_date %>
                <% end %>
              </td>
              <td><%= reservation.start_time.strftime("%H:%M") %></td>
              <td><%= reservation.num_children + reservation.num_students + reservation.num_adults %></td>
              <% if reservation.is_active == true %>
                <td class="text text-success">有効</td>
              <% else %>
                <td class="text text-danger">キャンセル</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/reservations/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-12 text-center bg-light">
      <h2><%= @reservation.start_date %> <%= @reservation.group_name %>様の予約詳細</h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-8 mx-auto">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="bg-light">幹事</td>
            <td><%= @reservation.user.last_name %> <%= @reservation.user.first_name %> 様</td>
          </tr>
          <tr>
            <td class="bg-light">団体名</td>
            <td><%= @reservation.group_name %> 様</td>
          </tr>
          <tr>
            <td class="bg-light">中学生以下の人数</td>
            <td><%= @reservation.num_children %> 人</td>
          </tr>
          <tr>
            <td class="bg-light">高校・大学・専門学生の人数</td>
            <td><%= @reservation.num_students %> 人</td>
          </tr>
          <tr>
            <td class="bg-light">一般の人数</td>
            <td><%= @reservation.num_adults %> 人</td>
          </tr>
          <tr>
            <td class="bg-light">ゲーム数</td>
            <td><%= @reservation.num_games %> ゲーム</td>
          </tr>
          <tr>
            <td class="bg-light">使用レーン数</td>
            <td><%= @reservation.num_lanes %> レーン</td>
          </tr>
          <tr>
            <td class="bg-light">スタート日時</td>
            <td><%= @reservation.start_date %> <%= @reservation.start_time.strftime("%H:%M") %></td>
          </tr>
          <tr>
            <td class="bg-light">備考</td>
            <td><%= @reservation.note %></td>
          </tr>
          <tr>
            <td class="bg-light">ゲーム代</td>
            <td><%= @reservation.games_fee.to_s(:delimited) %> 円</td>
          </tr>
          <tr>
            <td class="bg-light">ステータス</td>
            <% if @reservation.is_active == true %>
              <td class="text text-success">有効</td>
            <% else %>
              <td class="text text-danger">キャンセル</td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <% if @lane_details.presence && @lane_details[0].name_1.presence %>
    <div class="row mt-4">
      <div class="col-12 mx-auto text-center">
        <table class="table table-bordered mt-2">
          <thead class="bg-light">
            <tr>
              <td></td>
              <td>第１投球者</td>
              <td>第２投球者</td>
              <td>第３投球者</td>
              <td>第４投球者</td>
            </tr>
          </thead>
          <tbody>
            <% array = (1..@reservation.num_lanes).to_a %>
            <% array.each do |i| %>
              <tr>
                <td><%= i %> レーン</td>
                <% if @lane_details[i-1].presence %>
                  <td><%= @lane_details[i-1].name_1 %></td>
                  <td><%= @lane_details[i-1].name_2 %></td>
                  <td><%= @lane_details[i-1].name_3 %></td>
                  <td><%= @lane_details[i-1].name_4 %></td>
                <% else %>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @reservation.start_date >= Date.current %>
    <div class="row mt-2">
      <div class="col-8 mx-auto text-center">
        <%= link_to "本日以降の予約一覧へ", admin_root_path, class: "btn btn-primary" %>
        <%= link_to "編集する", edit_admin_reservation_path(@reservation.id), class: "btn btn-success mx-5" %>
        <%= link_to "削除する", admin_reservation_path(@reservation.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger" %>
      </div>
    </div>
  <% else %>
    <div class="row mt-2">
      <div class="col-8 mx-auto text-center">
        <%= link_to "前日までの予約一覧へ", admin_reservations_path, class: "btn btn-primary" %>
        <%= link_to "編集する", edit_admin_reservation_path(@reservation.id), class: "btn btn-success mx-5" %>
        <%= link_to "削除する", admin_reservation_path(@reservation.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>