config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "homes#top"
  end

  get "/admin/recent_registrated_reservation" => "admin/homes#about", as: "admin_about"

  root to: "public/homes#top"
  get "/fee" => "public/homes#about", as: "fee"
  get "/lane_status" => "public/homes#lane_status", as: "lane_status"
  get "/map" => "public/homes#map", as: "map"

  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :notifications, only: [:index]
  end

  post "/admin/num_lanes" => "admin/start_dates#num_lanes", as: "admin_num_lanes"
  namespace :admin do
    resources :start_dates, only: [:create, :index, :show, :edit, :update]
  end

  namespace :admin do
    resources :reservations, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: "public" do
    resources :reviews, only: [:index, :create, :edit, :update, :destroy]
  end

  get "/users/my_page" => "public/users#show", as: "my_page"
  get "/users/information/edit" => "public/users#edit", as: "edit_user_information"
  patch "/users/information" => "public/users#update", as: "update_user_information"

  scope module: "public" do
    resources :reservations, only: [:new, :index, :show]
  end
  post "/reservations/select_time" => "public/reservations#select_time", as: "select_time"
  post "/reservations/confirm" => "public/reservations#confirm", as: "confirm"
  post "/reservations/create" => "public/reservations#create", as: "create"
  post "/reservations/members_table" => "public/reservations#members_table", as: "members_table"
  get "/complete" => "public/reservations#complete", as: "complete"
  get "/reservations/:id/confirm_cancel" => "public/reservations#confirm_cancel", as: "confirm_cancel"
  patch "/reservations/:id/cancel" => "public/reservations#cancel", as: "cancel"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/start_date.rb
class StartDate < ApplicationRecord
  has_many :start_times, dependent: :destroy
  accepts_nested_attributes_for :start_times, allow_destroy: true

  validates :start_date, presence: true
end

app/controllers/admin/start_dates_controller.rb
class Admin::StartDatesController < ApplicationController
  before_action :set_beginning_of_week

  def index
    @start_date = StartDate.new
    @start_times = 20.times{@start_date.start_times.build}
    @reservations = Reservation.all
  end

  def num_lanes
    @start_date = StartDate.new(start_date_params)
    @start_times = 20.times{@start_date.start_times.build}
    render :num_lanes
  end

  def create
    @start_date = StartDate.new(start_date_params)
    @start_date.save
    redirect_to "/admin/start_dates?start_date=#{@start_date.start_date}"
  end

  def show
    @start_date = StartDate.find(params[:id])
    start_times = @start_date.start_times.all
    @start_times_first = start_times.first(10)
    @start_times_second = start_times.last(10)
    @reservations = Reservation.where(start_date: @start_date.start_date, is_active: true)
  end

  def edit
    @start_date = StartDate.find(params[:id])
    @start_times = @start_date.start_times.all
  end

  def update
    @start_date = StartDate.find(params[:id])
    @start_date.update(start_date_params)
    redirect_to admin_start_date_path(@start_date.id)
  end

  def destroy
    start_date = StartDate.find(params[:id])
    start_date.destroy
    redirect_to admin_start_dates_path
  end

  private

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end

  def start_date_params
    params.require(:start_date).permit(:start_date, :is_active,
      start_times_attributes: [:id, :start_time, :num_available_lanes]
    )
  end
end

app/helpers/admin/start_dates_helper.rb
module Admin::StartDatesHelper
end

app/views/admin/start_dates/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-8 mx-auto text-center bg-light">
      <% days = ["日", "月", "火", "水", "木", "金", "土"] %>
      <h2><%= @start_date.start_date %> (<%= days[@start_date.start_date.wday] %>) 残レーン数の編集</h2>
    </div>
  </div>

  <%= form_with model: @start_date, url: admin_start_date_path(@start_date.id), method: :patch do |f| %>
    <div class="row mt-4">
      <div class="col-8 mx-auto text-center">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <td>時間</td>
              <td>残レーン数</td>
            </tr>
          </thead>
          <tbody>
            <% times = ["11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30"] %>
            <%= f.fields_for :start_times do |start_time_field| %>
              <tr>
                <td><%= times[start_time_field.index] %></td>
                <td><%= start_time_field.select :num_available_lanes, *[0..24] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-12 mx-auto text-center">
        <span>予約不可能な日としますか？</span>
        <%= f.radio_button :is_active, false, class: "ml-2" %>
        <%= f.label :is_active_false, "YES" %>
        <%= f.radio_button :is_active, true, class: "ml-4" %>
        <%= f.label :is_active_true, "NO" %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-6 mx-auto text-center">
        <%= f.submit "編集内容を保存", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/start_dates/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-4 text-center bg-light">
      <h2>カレンダー</h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12 mx-auto text-center">
      <%= month_calendar do |date| %>
        <!-- 既に残レーンが登録されている日付の場合 -->
        <% if StartDate.find_by("start_date = ?", date) %>
          <%= link_to(admin_start_date_path(StartDate.find_by(start_date: date).id), style: "color: black") do %>
            <%= date.day %>
            <!-- 予約が入っている場合は、その予約件数を表示する -->
            <% if Reservation.where(start_date: date, is_active: true).exists? %>
              <p></p>
              <p class="bg-primary text-white"><%= Reservation.where(start_date: date, is_active: true).count %>件</p>
            <% end %>
            <!-- 予約不可能な日付には、バツ印をつける -->
            <% if StartDate.find_by(start_date: date).is_active == false %>
              <h1 class="text text-danger">×</h1>
            <% end %>
          <% end %>

        <!-- まだ残レーン数が登録されていない日付の場合 -->
        <% else %>
          <%= date.day %>
          <!-- ３ヶ月先までは残レーンの入力を受け付ける -->
          <% if date <= Date.current.since(3.month) %>
            <%= form_with model: @start_date, url: admin_num_lanes_path, method: :post do |f| %>
              <%= f.hidden_field :start_date, :value => date %>
              <%= f.submit "残レーン入力", class: "btn btn-success" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/start_dates/num_lanes.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-8 mx-auto text-center bg-light">
      <h2><%= @start_date.start_date %> の残レーン数入力</h2>
    </div>
  </div>

  <%= form_with model: @start_date, url: admin_start_dates_path, method: :post do |f| %>
    <%= f.hidden_field :start_date %>
    <div class="row mt-4">
      <div class="col-8 mx-auto text-center">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <td>時間</td>
              <td>残レーン数</td>
            </tr>
          </thead>
          <tbody>
            <% times = ["11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30"] %>
            <%= f.fields_for :start_times do |start_time_field| %>
              <tr>
                <td><%= times[start_time_field.index] %></td>
                <%= start_time_field.hidden_field :start_time, :value => times[start_time_field.index] %>
                <td><%= start_time_field.select :num_available_lanes, *[0..24], {selected: 24} %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-12 mx-auto text-center">
        <span>予約不可能な日としますか？</span>
        <%= f.radio_button :is_active, false, class: "ml-2" %>
        <%= f.label :is_active_false, "YES" %>
        <%= f.radio_button :is_active, true, checked: "checked", class: "ml-4" %>
        <%= f.label :is_active_true, "NO" %>
      </div>
    </div>

    <div class="row mt-2">
      <div class="col-6 mx-auto text-center">
        <%= f.submit "登録する", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/start_dates/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-8 mx-auto text-center bg-light">
      <% days = ["日", "月", "火", "水", "木", "金", "土"] %>
      <h2><%= @start_date.start_date %> (<%= days[@start_date.start_date.wday] %>) の詳細</h2>
    </div>
  </div>

  <% if @start_date.is_active == true %>
    <div class="row mt-4">
      <div class="col-4 text-center">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <td>時間</td>
              <td>残レーン数</td>
            </tr>
          </thead>
          <tbody>
            <% @start_times_first.each do |start_time_first| %>
              <tr>
                <td><%= start_time_first.start_time.strftime("%H:%M") %></td>
                <td><%= start_time_first.num_available_lanes %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-4 text-center">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <td>時間</td>
              <td>残レーン数</td>
            </tr>
          </thead>
          <tbody>
            <% @start_times_second.each do |start_time_second| %>
              <tr>
                <td><%= start_time_second.start_time.strftime("%H:%M") %></td>
                <td><%= start_time_second.num_available_lanes %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col-4 text-center">
        <table class="table table-bordered">
          <thead class="bg-light">
            <tr>
              <td scope="col" style="width: 50%">団体名</td>
              <td scope="col" style="width: 20%">人数</td>
              <td scope="col" style="width: 30%">スタート時間</td>
            </tr>
          </thead>
          <tbody>
            <% @reservations.each do |reservation| %>
              <tr>
                <td>
                  <%= link_to(admin_reservation_path(reservation.id), style: "color: black; text-decoration: underline") do %>
                    <%= reservation.group_name %>
                  <% end %>
                </td>
                <td><%= reservation.num_children + reservation.num_students + reservation.num_adults %></td>
                <td><%= reservation.start_time.strftime("%H:%M") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <div class="row mt-5">
      <div class="col-12 text-center h1">予約不可能な日です</div>
    </div>
  <% end %>

  <% @yesterday = StartDate.find_by(start_date: @start_date.start_date.ago(1.day)) %>
  <% @tomorrow = StartDate.find_by(start_date: @start_date.start_date.since(1.day)) %>
  <div class="row mt-2">
    <div class="col-10 mx-auto text-center">
      <% if @yesterday.presence %>
        <%= link_to "前の日", admin_start_date_path(@yesterday.id), class: "btn btn-primary mr-4" %>
      <% end %>
      <% if @start_date.start_date > Date.current %>
        <%= link_to "残レーン数を編集", edit_admin_start_date_path(@start_date.id), class: "btn btn-success" %>
      <% end %>
      <% if @tomorrow.presence %>
        <%= link_to "次の日", admin_start_date_path(@tomorrow.id), class: "btn btn-primary ml-4" %>
      <% end %>
    </div>
  </div>
</div>