config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "homes#top"
  end

  get "/admin/recent_registrated_reservation" => "admin/homes#about", as: "admin_about"

  root to: "public/homes#top"
  get "/fee" => "public/homes#about", as: "fee"
  get "/lane_status" => "public/homes#lane_status", as: "lane_status"
  get "/map" => "public/homes#map", as: "map"

  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :notifications, only: [:index]
  end

  post "/admin/num_lanes" => "admin/start_dates#num_lanes", as: "admin_num_lanes"
  namespace :admin do
    resources :start_dates, only: [:create, :index, :show, :edit, :update]
  end

  namespace :admin do
    resources :reservations, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: "public" do
    resources :reviews, only: [:index, :create, :edit, :update, :destroy]
  end

  get "/users/my_page" => "public/users#show", as: "my_page"
  get "/users/information/edit" => "public/users#edit", as: "edit_user_information"
  patch "/users/information" => "public/users#update", as: "update_user_information"

  scope module: "public" do
    resources :reservations, only: [:new, :index, :show]
  end
  post "/reservations/select_time" => "public/reservations#select_time", as: "select_time"
  post "/reservations/confirm" => "public/reservations#confirm", as: "confirm"
  post "/reservations/create" => "public/reservations#create", as: "create"
  post "/reservations/members_table" => "public/reservations#members_table", as: "members_table"
  get "/complete" => "public/reservations#complete", as: "complete"
  get "/reservations/:id/confirm_cancel" => "public/reservations#confirm_cancel", as: "confirm_cancel"
  patch "/reservations/:id/cancel" => "public/reservations#cancel", as: "cancel"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lane_detail.rb
class LaneDetail < ApplicationRecord
  belongs_to :reservation

  validates :name_1, presence: true
  validates :name_2, presence: true
  validates :name_3, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :reservation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :lane_details, dependent: :destroy
  accepts_nested_attributes_for :lane_details, allow_destroy: true
  has_many :notifications, dependent: :destroy

  validates :group_name, presence: true
  validates :num_children, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_students, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_adults, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_games, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :num_lanes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :start_date, presence: true
  validates :start_time, presence: true, format: {with: /[1-2][0-9]:[0-5][0-9]/}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/start_date.rb
class StartDate < ApplicationRecord
  has_many :start_times, dependent: :destroy
  accepts_nested_attributes_for :start_times, allow_destroy: true

  validates :start_date, presence: true
end

app/models/start_time.rb
class StartTime < ApplicationRecord
  belongs_to :start_date

  validates :start_time, presence: true, format: {with: /[1-2][0-9]:[0-5][0-9]/}
  validates :num_available_lanes, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  katakana = /\A[\p{katakana}\u{30fc}]+\z/

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: katakana, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: katakana, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true}
  validates :email, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    reservations = Reservation.page(params[:page]).where("start_date >= ?", Date.current)
    @reservations = reservations.order(start_date: :asc, start_time: :asc)
  end

  def about
    @reservation_today = Reservation.where(created_at: Time.zone.now.all_day).order(start_date: :asc, start_time: :asc)
    @reservation_yesterday = Reservation.where(created_at: 1.day.ago.all_day).order(start_date: :asc, start_time: :asc)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations.where(is_active: true).order(created_at: :desc).first(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/start_dates_helper.rb
module Admin::StartDatesHelper
end

app/helpers/admin/start_times_helper.rb
module Admin::StartTimesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mt-3">
      <h2 class="bg-light text-center">
        <%= @user.last_name %> <%= @user.first_name %>さんの会員情報編集
      </h2>
      <% if @user.errors.any? %>
        <h4><%= @user.errors.count %>件のエラーが発生しました</h4>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
    <div class="row mt-4">
      <div class="col-1"></div>
      <div class="col-3">
        <p>名前</p>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "w-100"; %>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :first_name, autocomplete: "first_name", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-1"></div>
      <div class="col-3">
        <p>フリガナ</p>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "w-100"; %>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-1"></div>
      <div class="col-3">
        <p>郵便番号(ハイフンなし)</p>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :postal_code, autocomplete: "postal_code", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-1"></div>
      <div class="col-3">
        <p>住所</p>
      </div>
      <div class="col-1"></div>
      <div class="col-7">
        <%= f.text_field :address, autocomplete: "address", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-1"></div>
      <div class="col-3">
        <p>電話番号(ハイフンなし)</p>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.text_field :telephone_number, autocomplete: "telephone_number", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-1"></div>
      <div class="col-3">
        <p>メールアドレス</p>
      </div>
      <div class="col-1"></div>
      <div class="col-3">
        <%= f.email_field :email, autocomplete: "email", class: "w-100"; %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-12 action text-center">
        <%= f.submit "編集内容を保存", class: "btn btn-success"; %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 mt-4">
      <h2 class="bg-light text-center">会員一覧</h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-10 mx-auto">
      <table class="table table-borderless">
        <thead class="table bg-info">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>予約回数</th>
            <th>直近の予約の実施日</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= link_to(admin_user_path(user.id), style: "color: black; text-decoration: underline") do %>
                  <%= user.last_name %> <%= user.first_name %>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <% if user.reservations.where(is_active: true).any? %>
                <td><%= user.reservations.where(is_active: true).count %></td>
                <% date = user.reservations.where(is_active: true).last.start_date %>
                <% days = ["日", "月", "火", "水", "木", "金", "土"] %>
                <td>
                  <%= link_to(admin_start_date_path(StartDate.find_by(start_date: date).id), style: "color: black; text-decoration: underline") do %>
                    <%= date %> (<%= days[date.wday] %>)
                  <% end %>
                </td>
              <% else %>
                <td>0</td>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mt-3">
      <h2 class="bg-light text-center">
        <%= @user.last_name %> <%= @user.first_name %>さんの会員・予約情報
      </h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-6 text-center">
      <p>会員情報</p>
    </div>
    <div class="col-6 text-center">
      <p>予約情報（最近の５件）</p>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="bg-light" scope="col" style="width: 30%">氏名</td>
            <td scope="col" style="width: 70%">
              <%= @user.last_name %>
              <%= @user.first_name %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">カナ</td>
            <td>
              <%= @user.last_name_kana %>
              <%= @user.first_name_kana %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">郵便番号</td>
            <td>
              <%= @user.postal_code %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">住所</td>
            <td>
              <%= @user.address %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">電話番号</td>
            <td>
              <%= @user.telephone_number %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">メールアドレス</td>
            <td>
              <%= @user.email %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to "会員情報編集", edit_admin_user_path(@user.id), class: "btn btn-success text-center" %>
      </div>
    </div>
    <div class="col-6">
      <table class="table table-bordered">
        <thead class="bg-light">
          <tr>
            <td scope="col" style="width: 35%">実施日</td>
            <td scope="col" style="width: 50%">団体名</td>
            <td scope="col" style="width: 15%">人数</td>
          </tr>
        </thead>
        <tbody>
          <% days = ["日", "月", "火", "水", "木", "金", "土"] %>
          <% @reservations.each do |reservation| %>
            <tr>
              <td>
                <%= link_to(admin_start_date_path(StartDate.find_by(start_date: reservation.start_date).id), style: "color: black; text-decoration: underline") do %>
                  <%= reservation.start_date %> (<%= days[reservation.start_date.wday] %>)
                <% end %>
              </td>
              <td>
                <%= link_to(admin_reservation_path(reservation.id), style: "color: black; text-decoration: underline") do %>
                  <%= reservation.group_name %>
                <% end %>
                </td>
              <td><%= reservation.num_children + reservation.num_students + reservation.num_adults %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>