config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "homes#top"
  end

  get "/admin/recent_registrated_reservation" => "admin/homes#about", as: "admin_about"

  root to: "public/homes#top"
  get "/fee" => "public/homes#about", as: "fee"
  get "/lane_status" => "public/homes#lane_status", as: "lane_status"
  get "/map" => "public/homes#map", as: "map"

  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :notifications, only: [:index]
  end

  post "/admin/num_lanes" => "admin/start_dates#num_lanes", as: "admin_num_lanes"
  namespace :admin do
    resources :start_dates, only: [:create, :index, :show, :edit, :update]
  end

  namespace :admin do
    resources :reservations, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: "public" do
    resources :reviews, only: [:index, :create, :edit, :update, :destroy]
  end

  get "/users/my_page" => "public/users#show", as: "my_page"
  get "/users/information/edit" => "public/users#edit", as: "edit_user_information"
  patch "/users/information" => "public/users#update", as: "update_user_information"

  scope module: "public" do
    resources :reservations, only: [:new, :index, :show]
  end
  post "/reservations/select_time" => "public/reservations#select_time", as: "select_time"
  post "/reservations/confirm" => "public/reservations#confirm", as: "confirm"
  post "/reservations/create" => "public/reservations#create", as: "create"
  post "/reservations/members_table" => "public/reservations#members_table", as: "members_table"
  get "/complete" => "public/reservations#complete", as: "complete"
  get "/reservations/:id/confirm_cancel" => "public/reservations#confirm_cancel", as: "confirm_cancel"
  patch "/reservations/:id/cancel" => "public/reservations#cancel", as: "cancel"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lane_detail.rb
class LaneDetail < ApplicationRecord
  belongs_to :reservation

  validates :name_1, presence: true
  validates :name_2, presence: true
  validates :name_3, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :reservation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :lane_details, dependent: :destroy
  accepts_nested_attributes_for :lane_details, allow_destroy: true
  has_many :notifications, dependent: :destroy

  validates :group_name, presence: true
  validates :num_children, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_students, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_adults, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :num_games, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :num_lanes, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :start_date, presence: true
  validates :start_time, presence: true, format: {with: /[1-2][0-9]:[0-5][0-9]/}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/start_date.rb
class StartDate < ApplicationRecord
  has_many :start_times, dependent: :destroy
  accepts_nested_attributes_for :start_times, allow_destroy: true

  validates :start_date, presence: true
end

app/models/start_time.rb
class StartTime < ApplicationRecord
  belongs_to :start_date

  validates :start_time, presence: true, format: {with: /[1-2][0-9]:[0-5][0-9]/}
  validates :num_available_lanes, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  katakana = /\A[\p{katakana}\u{30fc}]+\z/

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: katakana, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: {with: katakana, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true}
  validates :email, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    reservations = Reservation.page(params[:page]).where("start_date >= ?", Date.current)
    @reservations = reservations.order(start_date: :asc, start_time: :asc)
  end

  def about
    @reservation_today = Reservation.where(created_at: Time.zone.now.all_day).order(start_date: :asc, start_time: :asc)
    @reservation_yesterday = Reservation.where(created_at: 1.day.ago.all_day).order(start_date: :asc, start_time: :asc)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations.where(is_active: true).order(created_at: :desc).first(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/start_dates_helper.rb
module Admin::StartDatesHelper
end

app/helpers/admin/start_times_helper.rb
module Admin::StartTimesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bowling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/feeb68efc8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to(root_path, class: "navbar-brand") do %>
            <span>佐藤翔ボウル</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <!-- 会員側でログインしている場合 -->
              <% if user_signed_in? %>
                <li>
                  <%= link_to(fee_path, class: "navbar-brand") do %>
                    <span>料金表</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(map_path, class: "navbar-brand") do %>
                    <span>マップ</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(lane_status_path, class: "navbar-brand") do %>
                    <span>残レーン状況</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_reservation_path, class: "navbar-brand") do %>
                    <span>予約ページ</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(reviews_path, class: "navbar-brand") do %>
                    <span>レビュー</span>
                  <% end %>
                </li>

              <!-- 管理者側でログインしている場合 -->
              <% elsif admin_signed_in? %>
                <li class="my-auto">
                  <%= link_to(lane_status_path, class: "navbar-brand") do %>
                    <span>残レーン状況</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(admin_users_path, class: "navbar-brand") do %>
                    <span>会員一覧</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(admin_about_path, class: "navbar-brand") do %>
                    <span>最近登録された予約</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(admin_root_path, class: "navbar-brand") do %>
                    <span>予約一覧(未)</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(admin_reservations_path, class: "navbar-brand") do %>
                    <span>予約一覧(済)</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(admin_start_dates_path, class: "navbar-brand") do %>
                    <span>カレンダー</span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(reviews_path, class: "navbar-brand") do %>
                    <span>レビュー</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(admin_notifications_path, class: "navbar-brand") do %>
                    <span class="fa-stack">
                      <i class="fa-solid fa-bell fa-stack-2x"></i>
                      <% if Notification.where(checked: false).any? %>
                        <i class="fa-solid fa-circle fa-stack-1x" style="color: orange; padding-top: 0.8rem; padding-left: 1.6rem;"></i>
                      <% end %>
                    </span>
                  <% end %>
                </li>
                <li class="my-auto">
                  <%= link_to(destroy_admin_session_path, method: :delete, class: "navbar-brand") do %>
                    <span>ログアウト</span>
                  <% end %>
                </li>

              <!-- ログインしていない場合 -->
              <% else %>
                <li>
                  <%= link_to(fee_path, class: "navbar-brand") do %>
                    <span>料金表</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(map_path, class: "navbar-brand") do %>
                    <span>マップ</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(lane_status_path, class: "navbar-brand") do %>
                    <span>残レーン状況</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(reviews_path, class: "navbar-brand") do %>
                    <span>レビュー</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_user_registration_path, class: "navbar-brand") do %>
                    <span>会員登録</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_user_session_path, class: "navbar-brand") do %>
                    <span>ログイン</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>

          <!-- 会員側でログインしている場合、ログインしている人の名前が表示されたドロップボタンを実装する -->
          <% if user_signed_in? %>
            <div class="dropdown">
              <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-person"></i> <%= current_user.last_name %> <%= current_user.first_name %>
              </button>
              <ul class="dropdown-menu">
                <li class="ml-4">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, style: "color: black;" %>
                </li>
                <li class="mt-2 ml-4">
                  <%= link_to "マイページ", my_page_path, style: "color: black;" %>
                </li>
                <li class="mt-2 ml-4">
                  <%= link_to "予約履歴一覧", reservations_path, style: "color: black;" %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <!-- 管理者側でログインしているときは、フッターは表示しない -->
    <% unless admin_signed_in? %>
      <div style="height: 200px;"></div>
      <footer class="bg-secondary py-4 text-white">
        <div class="container">
          <div class="row">
            <div class="col-6 mx-auto">
              <p>〒○○○-○○○○</p>
              <p>○○県△△市□□町××</p>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-6 mx-auto">
              <i class="fa-solid fa-phone mr-1"></i><span class="mr-4">xxx-yyy-zzzz</span>
              <i class="fa-regular fa-envelope ml-4"></i><span class="ml-1">satokakeru_bowl@gmail.com</span>
            </div>
          </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>